server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_test_db
    username: payment_user
    password: payment_secret
  flyway:
    enabled: false

payment:
  gateway: fake
  api-key: test-api-key
  fake-gateway-webhook-secret: test-secret-key
  dev:
    enabled: true
  scheduler:
    enabled: false
